let scannerStream=null, scannerWorker=null, scannerBusy=false, scannerMode='global', lastScanFile=null;
const scan=$=>document.getElementById($);
const machineModel=/\b(?:S0[137]|TLF|TCP|BMC[- ]?[SA]|CCS|FAC|HCA|PGS|TFC|TL[- ]?LINE|WAS|TE)\b/i;
function openScanner(){scan('scanner').classList.add('open');scan('scanStatus').textContent='Camera paused. Start camera or upload an image.'}
function closeScanner(){stopCamera();scan('scanner').classList.remove('open')}
async function startCamera(){try{scan('scanVideo').style.display='block';scan('scanPreview').style.display='none';scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});scan('scanVideo').srcObject=scannerStream;await scan('scanVideo').play();scan('scanCameraHint').style.display='none';scan('scanStatus').textContent='Point at any plate, machine, motor, valve, sensor or component.'}catch(e){scan('scanStatus').textContent='Camera unavailable. Use Upload image instead.'}}
function stopCamera(){if(scannerStream){scannerStream.getTracks().forEach(t=>t.stop());scannerStream=null}if(scan('scanVideo'))scan('scanVideo').srcObject=null}
function showPreview(file){const img=scan('scanPreview');if(!img)return;img.src=URL.createObjectURL(file);img.style.display='block';scan('scanVideo').style.display='none';scan('scanCameraHint').style.display='none'}
function capturePlate(){scan('scanStatus').textContent='Capturing image…';const v=scan('scanVideo');if(!v.videoWidth){scan('scanStatus').textContent='Start the camera first.';return}const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);c.toBlob(b=>{lastScanFile=b;showPreview(b);runScan(b)},'image/jpeg',.94)}
function setMode(mode){scannerMode=mode;scan('modeLocal').classList.toggle('active',mode==='local');scan('modeGlobal').classList.toggle('active',mode==='global');scan('scanStatus').textContent=mode==='global'?'Global mode: OCR + optional secure visual AI + public-source research.':'Local mode: OCR + local machine library.'}
async function runScan(file){if(!file)return;if(scannerBusy){scan('scanStatus').textContent='A scan is already processing…';return}scannerBusy=true;lastScanFile=file;showPreview(file);scan('scanStatus').textContent=scannerMode==='global'?'Image received. Reading locally, then preparing global research…':'Image received. Reading text locally…';scan('scanRun').disabled=true;if(scan('scanDetect'))scan('scanDetect').disabled=true;try{if(!window.Tesseract)throw Error('OCR runtime unavailable');if(!scannerWorker){scannerWorker=await Tesseract.createWorker('eng',1,{workerPath:'./vendor/ocr/dist/worker.min.js',corePath:'./vendor/ocr/tesseract-core-simd-lstm.wasm.js',langPath:'./vendor/ocr/tessdata'});await scannerWorker.setParameters({tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-+/ :.'})}const {data}=await scannerWorker.recognize(file);const text=data.text||'';scan('scanText').value=text;matchPlate(text);if(scannerMode==='global')await runGlobalResearch(file,text);else{scan('scanStatus').textContent='Detection complete. Confirm the detected record or switch to Global AI + web.';renderGlobalResults([])}}catch(e){console.error(e);scan('scanStatus').textContent='Image loaded, but OCR could not start. Edit the plate text or press Run detection again.';if(scannerMode==='global')await runGlobalResearch(file,'')}finally{scannerBusy=false;scan('scanRun').disabled=false;if(scan('scanDetect'))scan('scanDetect').disabled=!lastScanFile}}
function matchPlate(text){const upper=text.toUpperCase().replace(/\s+/g,' ');let found=null;const code=(upper.match(machineModel)||[])[0]?.replace(/ /g,'');if(code)found=window.machines?.find(m=>m.model.toUpperCase().replace(/ /g,'').includes(code));const serial=(upper.match(/(?:SERIAL|SERIA[L1]|S\/N)\s*(?:NO)?\s*[:.]?\s*([A-Z0-9-]+)/i)||[])[1];if(serial)scan('scanSerial').value=serial;scan('scanModel').value=found?.model||code||scan('scanModel').value;scan('scanDetected').textContent=found?`Detected: ${found.model} · ${found.name}`:'No exact local model code detected — use Global AI + web';scan('scanDetected').dataset.good=!!found;scan('scanOpen').disabled=!found;if(found)window.scannedMachine=found}
async function runGlobalResearch(file,text){scan('scanStatus').textContent='Global mode: checking visual AI route and public sources…';let result=null;let visualError='';try{const b64=await fileToDataURL(file);const r=await fetch('/api/global-identify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({image:b64,text})});const data=await r.json().catch(()=>({}));if(r.ok)result=data;else visualError=data.detail||data.error||`HTTP ${r.status}`}catch(e){visualError=e.message||'Visual AI route unavailable'}const query=(result?.query||scan('scanModel').value||text.split(/\n/).filter(Boolean).slice(0,2).join(' ')).trim();let publicResults=[];if(query)try{const r=await fetch('https://www.wikidata.org/w/api.php?action=wbsearchentities&search='+encodeURIComponent(query)+'&language=en&format=json&origin=*');const j=await r.json();publicResults=(j.search||[]).slice(0,5).map(x=>({title:x.label||x.id,description:x.description||'Wikidata entity',url:'https://www.wikidata.org/wiki/'+x.id,source:'Wikidata'}))}catch(e){}renderGlobalResults([...(result?.results||[]),...publicResults]);scan('scanStatus').textContent=result?'Detection complete. Review confidence and sources before relying on the result.':query?'OCR/public research complete. Visual AI was unavailable, so verify the result against the physical plate.':`Image loaded. ${visualError||'No readable plate text was found.'} Add or edit the plate text, then run detection again.`}
function fileToDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function renderGlobalResults(items){const box=scan('globalResults');if(!items.length){box.innerHTML='<b>Global research results</b><span>No global result yet. Use Global AI + web to analyze unknown machines and components.</span>';return}box.innerHTML='<b>Global research results</b>'+items.slice(0,6).map(x=>`<div><strong>${x.title||x.name||'Possible identification'}</strong><br><span>${x.confidence?`Confidence: ${x.confidence} · `:''}${x.description||x.reason||'Review this candidate against the image and nameplate.'}</span>${x.url?`<br><a href="${x.url}" target="_blank" rel="noopener">${x.source||'Open source'} ↗</a>`:''}</div>`).join('')}
function openDetected(){if(window.scannedMachine){closeScanner();window.openModal(window.scannedMachine.id);window.setJarvisMachine?.(window.scannedMachine);window.loadMachineModel?.(window.scannedMachine)}}
function bindScanner(){const ids=['scanStart','scanCapture','scanRun','scanFile','scanOpen','scanClose','scanText','modeLocal','modeGlobal'];if(!ids.every(id=>scan(id)))return;scan('scanStart').addEventListener('click',startCamera);scan('scanCapture').addEventListener('click',capturePlate);const chooseFile=()=>{scan('scanStatus').textContent='Choose a plate or component image…';scan('scanFile').click()};scan('scanRun').addEventListener('click',chooseFile);document.getElementById('uploadGlobal')?.addEventListener('click',()=>{openScanner();setTimeout(chooseFile,80)});scan('scanFile').addEventListener('change',e=>{if(e.target.files[0]){lastScanFile=e.target.files[0];if(scan('scanDetect'))scan('scanDetect').disabled=false;runScan(e.target.files[0])}});scan('scanDetect')?.addEventListener('click',()=>runScan(lastScanFile));scan('scanOpen').addEventListener('click',openDetected);scan('scanClose').addEventListener('click',closeScanner);scan('scanText').addEventListener('input',e=>matchPlate(e.target.value));scan('modeLocal').addEventListener('click',()=>setMode('local'));scan('modeGlobal').addEventListener('click',()=>setMode('global'));document.querySelectorAll('[data-scan]').forEach(b=>b.addEventListener('click',openScanner));return true}if(!bindScanner())window.addEventListener('DOMContentLoaded',bindScanner);
window.addEventListener('DOMContentLoaded',()=>setMode('global'));
