import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root=path.dirname(fileURLToPath(import.meta.url));
const port=Number(process.env.PORT||10000);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.gltf':'model/gltf+json','.bin':'application/octet-stream','.pdf':'application/pdf','.wasm':'application/wasm','.svg':'image/svg+xml'};
const json=(res,data,status=200)=>{res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(data))};
async function body(req){let s='';for await(const c of req)s+=c;return JSON.parse(s||'{}')}
async function jarvis(req,res){const {system='',messages=[]}=await body(req);const g=process.env.GEMINI_API_KEY;
 if(g){const requested=process.env.GEMINI_MODEL?.trim();const models=[...new Set([requested,'gemini-2.5-flash','gemini-2.0-flash','gemini-2.0-flash-lite','gemini-1.5-flash'].filter(Boolean))];const contents=messages.map(x=>({role:x.role==='assistant'?'model':'user',parts:[{text:String(x.content)}]}));let last='';for(const model of models){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${g}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents,generationConfig:{temperature:.2,maxOutputTokens:900}})});const j=await r.json().catch(()=>({}));if(r.ok){return json(res,{text:j.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'No response generated.',provider:'Gemini '+model})}last=j.error?.message||`Gemini model ${model} returned ${r.status}`;}catch(e){last=e.message}}return json(res,{error:'Gemini provider rejected the request',detail:last,modelsTried:models},502)}
 const key=process.env.OPENAI_API_KEY;if(!key)return json(res,{error:'No AI provider configured. Set GEMINI_API_KEY or OPENAI_API_KEY on Render.'},503);const base=process.env.OPENAI_API_BASE||'https://api.openai.com/v1';const r=await fetch(base+'/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.JARVIS_MODEL||'gpt-4o-mini',temperature:.2,max_tokens:900,messages:[{role:'system',content:system},...messages]})});if(!r.ok)return json(res,{error:'OpenAI-compatible request failed'},502);const j=await r.json();return json(res,{text:j.choices?.[0]?.message?.content||'No response generated.',provider:'OpenAI-compatible'})}
async function identify(req,res){const {image,text=''}=await body(req);const g=process.env.GEMINI_API_KEY;const prompt=`Identify visible industrial machines/components from this image. OCR text: ${text}. Return JSON only with query and results. Each result needs title, confidence low/medium/high, description, reason, and url if known. Never claim an exact part number from appearance alone.`;
 if(g){const model=process.env.GEMINI_MODEL||'gemini-2.0-flash-lite';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${g}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt},{inline_data:{mime_type:'image/jpeg',data:String(image).split(',')[1]||image}}]}],generationConfig:{temperature:.1,maxOutputTokens:1100}})});if(!r.ok){const e=await r.json().catch(()=>({}));return json(res,{error:'Gemini visual request failed',detail:e.error?.message||`HTTP ${r.status}`},502)}const j=await r.json();let raw=j.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'{}';raw=raw.replace(/^```json\s*|\s*```$/g,'');try{return json(res,{...JSON.parse(raw),source:'Gemini '+model})}catch{return json(res,{query:text,results:[{title:'Gemini visual assessment',confidence:'low',description:raw,reason:'Review the image and nameplate'}],source:'Gemini '+model})}}
 return json(res,{error:'Visual AI is not configured. Set GEMINI_API_KEY on Render.',results:[]},503)}
async function search(req,res){const q=new URL(req.url,'http://localhost').searchParams.get('q')?.trim()||'';if(!q)return json(res,{results:[]});const get=u=>fetch(u).then(r=>r.json());const [w,d,dd]=await Promise.allSettled([get(`https://en.wikipedia.org/w/rest.php/v1/search/page?q=${encodeURIComponent(q)}&limit=6`),get(`https://www.wikidata.org/w/api.php?action=wbsearchentities&search=${encodeURIComponent(q)}&language=en&format=json&limit=6&origin=*`),get(`https://api.duckduckgo.com/?q=${encodeURIComponent(q)}&format=json&no_html=1&skip_disambig=1`)]);const out=[];if(w.status==='fulfilled')for(const x of w.value.pages||[])out.push({source:'Wikipedia',title:x.title,description:x.description||x.excerpt||'',url:'https://en.wikipedia.org/wiki/'+encodeURIComponent((x.key||x.title).replaceAll(' ','_'))});if(d.status==='fulfilled')for(const x of d.value.search||[])out.push({source:'Wikidata',title:x.label||x.id,description:x.description||'',url:'https://www.wikidata.org/wiki/'+x.id});if(dd.status==='fulfilled'&&dd.value.AbstractText)out.unshift({source:'DuckDuckGo public index',title:dd.value.Heading||q,description:dd.value.AbstractText,url:dd.value.AbstractURL});return json(res,{query:q,results:out})}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/health')return json(res,{ok:true});if(u.pathname==='/api/jarvis'&&req.method==='POST')return await jarvis(req,res);if(u.pathname==='/api/global-identify'&&req.method==='POST')return await identify(req,res);if(u.pathname==='/api/global-search')return await search(req,res);let rel=decodeURIComponent(u.pathname);if(rel==='/'||rel==='')rel='/index.html';const file=path.resolve(root,'.'+rel);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return res.writeHead(404).end('Not found');res.writeHead(200,{'content-type':mime[path.extname(file).toLowerCase()]||'application/octet-stream'});fs.createReadStream(file).pipe(res)}catch(e){console.error(e);json(res,{error:'Server error'},500)}});
server.listen(port,'0.0.0.0',()=>console.log(`Universal Engineer server listening on ${port}`));
