import * as THREE from './vendor/three.module.js';
import { GLTFLoader } from './vendor/GLTFLoader.js';
const canvas=document.getElementById('scene'), host=canvas?.closest('.viewer');
if(!canvas||!host) throw new Error('3D viewer canvas missing');
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x000000,0)}catch(e){console.error(e);document.getElementById('modelSelected').textContent='WebGL is unavailable in this browser';throw e}
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,1,.01,100);camera.position.set(8,5.5,9);
scene.add(new THREE.HemisphereLight(0xb8ddff,0x061331,2.3));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(5,8,7);scene.add(key);
const root=new THREE.Group();scene.add(root);const loader=new GLTFLoader();let current=null,model=null,exploded=false,wire=false,autoRotate=false;let target=new THREE.Vector3(),distance=13,azimuth=.65,elevation=.38;let dragging=false,pan=false,last={x:0,y:0};
const ui=document.createElement('div');ui.className='model-overlay';ui.innerHTML='<span class="model-badge">CONCEPTUAL GLTF / X-RAY VIEW</span><span id="modelSelected">Select a component</span>';host.appendChild(ui);
function resize(){const r=host.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();
function frame(){const x=target.x+distance*Math.cos(elevation)*Math.sin(azimuth),y=target.y+distance*Math.sin(elevation),z=target.z+distance*Math.cos(elevation)*Math.cos(azimuth);camera.position.set(x,y,z);camera.lookAt(target)}
function materials(){if(!model)return;model.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=wire?.9:((o.material.name||'').includes('Transparent')?.28:.94);o.material.wireframe=wire;o.material.depthWrite=!((o.material.name||'').includes('Transparent'));}})}
function populateTree(){const tree=document.getElementById('componentTree');if(!tree||!model)return;tree.innerHTML='';model.traverse(o=>{if(o.isMesh){const b=document.createElement('button');b.className='component-row';b.textContent=o.name;b.onclick=()=>{model.traverse(x=>{if(x.isMesh)x.material.emissive?.setHex(0)});o.material.emissive?.setHex(0x1b76c9);document.getElementById('modelSelected').textContent=o.name;};tree.appendChild(b)}})}
function applyExplode(){if(!model)return;let i=0;model.traverse(o=>{if(o.isMesh){const dir=o.position.clone();if(dir.length()<.01)dir.set((i%3)-1,((i+1)%3)-1,((i+2)%3)-1);dir.normalize();o.position.copy(exploded?dir.multiplyScalar(.35):new THREE.Vector3());i++}})}
window.loadMachineModel=async function(m){current=m;if(model)root.remove(model);document.getElementById('viewModel').textContent=m.model+' · '+m.name.toUpperCase();document.getElementById('modelSelected').textContent='Loading '+m.name+'…';try{const gltf=await loader.loadAsync(m.model3d.path);model=gltf.scene;root.add(model);model.rotation.y=.25;model.scale.setScalar(1.25);model.traverse(o=>{if(o.isMesh)o.userData.component=o.name});distance=13;azimuth=.65;elevation=.38;frame();materials();populateTree();document.getElementById('modelSelected').textContent='Conceptual model · select a component';}catch(e){console.error(e);document.getElementById('modelSelected').textContent='Model load error';}};
canvas.addEventListener('pointerdown',e=>{dragging=true;pan=e.shiftKey||e.button===2;last={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-last.x,dy=e.clientY-last.y;last={x:e.clientX,y:e.clientY};if(pan){target.x-=dx*.012;target.y+=dy*.012}else{azimuth-=dx*.012;elevation=Math.max(-1.1,Math.min(1.1,elevation-dy*.012))}frame()});canvas.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(4,Math.min(30,distance*(1+e.deltaY*.001)));frame()},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
document.getElementById('explode')?.addEventListener('click',()=>{exploded=!exploded;applyExplode();document.getElementById('explode').classList.toggle('on',exploded)});document.getElementById('wire')?.addEventListener('click',()=>{wire=!wire;materials();document.getElementById('wire').classList.toggle('on',wire)});document.getElementById('opacity')?.addEventListener('input',e=>{if(!model)return;model.traverse(o=>{if(o.isMesh)o.material.opacity=+e.target.value/100})});document.getElementById('resetView')?.addEventListener('click',()=>{target.set(0,0,0);distance=13;azimuth=.65;elevation=.38;frame()});
window.addEventListener('catalog:ready',e=>{if(e.detail)window.loadMachineModel(e.detail)});function tick(){if(autoRotate){azimuth+=.004;frame()}renderer.render(scene,camera);requestAnimationFrame(tick)}frame();tick();
